### ISSUE TITLE
Update causing fatal crashes

### ISSUE THREAD

**Issue by DoranVakhrushev** [zhukov/webogram#1582]
Ever since I downloaded the update on December 30th (earlier tonight) My phone refuses to open the app. I tap the app, it attempts to launch, but crashes before I get in.
-iPhone 4s
-iOS 7.1.2
-not jailbroken
Just want to make the problem known

**Comment by zhukov** [comment]
@DoranVakhrushev What is the iOS version?

**Comment by DoranVakhrushev** [comment]
@zhukov I edited it into the post a few minutes ago, 7.1.2

**Comment by zhukov** [comment]
can you try again? I've just pushed some fixes

**Comment by DoranVakhrushev** [comment]
I've tried again, sadly same problem. I even reinstalled the app all together, but it still crashes upon launch.

**Comment by DoranVakhrushev** [comment]
I'm not sure what changed, but webogram is now functioning whereas the telegram app is not! I appreciate the response and fixes made.

**Comment by azzimuth** [comment]
Wait. This repository has nothing to do with the mobile apps!
